#!/bin/sh

RS_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.rs$")
if [ -n "${RS_FILES}" ]; then
    echo "cargo fmt --all"
    (
      cargo fmt --all
    )
    # shellcheck disable=SC2046
    # removing git add does not apply formatting before commit,
    # but it allows to use intellij interactive commits
    # git add $(echo "$RS_FILES" | paste -s -d " " -)
fi